<?php
/**
 * WordPress OAuth Functions
 * @author Justin Greer <justin@justin-greer.com>
 * @package WordPress OAuth Server
 */


/**
 * Create a client in the system
 * @return [type] [description]
 */
function wo_create_client ()
{

}

/**
 * Generate a key 
 * A 60 Charecter key is generated by default but should be adjustable in the admin
 * @return [type] [description]
 */
function wo_gen_key($length=60)
{

}