<?php
/**
 * WordPress OAuth Functions
 * @author Justin Greer <justin@justin-greer.com>
 * @package WordPress OAuth Server
 */


/**
 * Create a client in the system
 * @return [type] [description]
 */
function wo_create_client ()
{

}

/**
 * Updates a client
 * @param  String $client_id ID if the cient to update
 * @param  Array $data      Data in hash with key values to update in the database
 * @return Bool          True is the update was successull
 */
function wo_edit_client ($client_id=null, $data)
{

}

/**
 * Generate a key 
 * A 60 Charecter key is generated by default but should be adjustable in the admin
 * @return [type] [description]
 *
 * @todo Allow more characters to be added to the character list to provide comlex keys
 */
function wo_gen_key($length=60)
{
  $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  $randomString = '';
  for ($i = 0; $i < $length; $i++) {
      $randomString .= $characters[rand(0, strlen($characters) - 1)];
  }
  return $randomString;
}